-- bootstrap-historie.sql — Verwaltungstabelle der Schema-Auslieferung
--
-- Läuft als ALLERERSTES bei jedem Container-Start, vor jedem Legacy-Skript und
-- vor dem Vollschema. Steht deshalb bewusst NICHT in base_schema.sql: die
-- Kettenlogik im Entrypoint muss die Tabelle bereits lesen können, während sie
-- entscheidet, ob base_schema.sql überhaupt allein genügt.
--
-- Modell entspricht Flyway (`flyway_schema_history`) bzw. Rails
-- (`schema_migrations`), mit deren zwei Eintragsarten:
--
--   art = 'legacy'      Einmal-Skript. Genau eine erfolgreiche Zeile je Datei.
--                       Ist eine da, wird die Datei nie wieder ausgeführt.
--   art = 'vollschema'  Wiederholbar (Flyway: "repeatable migration"). Läuft bei
--                       JEDEM Start; eine neue Zeile entsteht nur, wenn sich die
--                       Checksumme gegenüber der letzten geändert hat. Ergibt
--                       nebenbei die Historie "wann sah diese DB welchen
--                       Schemastand".
--
-- Kein CHECK auf `ergebnis` — gleiche Begründung wie bei _jobs.status und
-- _dr_sessions.status: ein CHECK im wiederholt laufenden Schema erzwingt
-- DROP+ADD gegen die Live-DB, sobald ein Wert dazukommt. Erlaubte Werte:
--   'laeuft'        Skript gestartet, Ausgang offen. Bleibt bei Absturz stehen
--                   und ist dann der Fundort für die Nachschau.
--   'erfolg'        Sauber durchgelaufen.
--   'fehler'        Abgebrochen. Der Entrypoint bricht dann ebenfalls ab.
--   'uebersprungen' Frische Installation: das Vollschema erzeugt den Zielzustand
--                   bereits vollständig, das Legacy-Skript wäre ein teurer
--                   No-op. Entspricht Rails `db:schema:load` + Eintragen aller
--                   Migrationen als erledigt.
CREATE SCHEMA IF NOT EXISTS postbuch;

CREATE TABLE IF NOT EXISTS postbuch._schema_historie (
    rang          integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skript        text         NOT NULL,
    art           text         NOT NULL,
    checksumme    text         NOT NULL,
    ergebnis      text         NOT NULL,
    app_version   text,
    angewendet_am timestamptz  NOT NULL DEFAULT now(),
    dauer_ms      integer
);

-- Nachschlagepfad der Kettenlogik: "gibt es zu dieser Datei schon ein
-- erledigtes Ergebnis?"
CREATE INDEX IF NOT EXISTS schema_historie_skript_idx
    ON postbuch._schema_historie USING btree (skript, ergebnis);
